//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediserv.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categories()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> CountProducts { get; set; }
        public Nullable<int> Shopcode { get; set; }
        public string Description { get; set; }
        public string Shortdescription { get; set; }
        public string isActive { get; set; }
        public Nullable<int> pro_fk_cat { get; set; }
        public string ImageUrl { get; set; }
        [NotMapped]
        public HttpPostedFileBase img { get; set; } 

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
