//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediserv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public int Contact_id { get; set; }
        public int UserId { get; set; }
    }
}
